---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/users/new":
    get:
      summary: new user
      responses:
        '200':
          description: successful
  "/api/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
