name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Setup RSpec
        run: |
          bundle install --jobs 4 --retry 3 --without production
          gem install --no-document rspec -v '>=3.0, < 4.0'
      - name: RSpec Report
        run: bundle exec rspec --force-color --format documentation
